apiVersion: flowctl/v1
kind: Pipeline
metadata:
    description: Process stellar contract events on testnet
    name: stellar-pipeline
spec:
    driver: process
    processors:
        - config:
            network_passphrase: Test SDF Network ; September 2015
          id: contract-events
          inputs:
            - stellar-source
          type: contract-events-processor@v1.0.0
    sinks:
        - config:
            database_path: ./stellar-pipeline.duckdb
          id: duckdb-sink
          inputs:
            - contract-events
          type: duckdb-consumer@v1.0.0
    sources:
        - config:
            backend_type: RPC
            network_passphrase: Test SDF Network ; September 2015
            rpc_endpoint: https://soroban-testnet.stellar.org
            start_ledger: 2191326
          id: stellar-source
          type: stellar-live-source@v1.0.0
