apiVersion: flowctl/v1
kind: Pipeline
metadata:
  name: test-pipeline
  description: Test pipeline for Docker Compose generation

version: 0.1
log_level: info

source:
  type: stellar-source
  params:
    image: ghcr.io/withobsrvr/stellar-live-source-datalake:latest
    command:
      - ./stellar_live_source_datalake
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/.config/gcloud/application_default_credentials.json
      STORAGE_TYPE: GCS
      BUCKET_NAME: obsrvr-stellar-ledger-data-testnet-data/landing/ledgers
      LEDGERS_PER_FILE: 1
      FILES_PER_PARTITION: 64000
      FLOWCTL_ENDPOINT: localhost:8080
    ports:
      - 50052
    health_check: /health

processors:
  - name: ttp-processor
    plugin: token-transfer
    params:
      image: ghcr.io/withobsrvr/ttp-processor:latest
      command:
        - ./ttp_processor_server
      env:
        SOURCE_SERVICE_ADDRESS: stellar-source:50052
        NETWORK_PASSPHRASE: Test SDF Network ; September 2015
        FLOWCTL_ENDPOINT: localhost:8080
        HEALTH_PORT: 8089
      ports:
        - 50053
        - 8089
      health_check: /health

sink:
  type: demo-consumer
  params:
    image: ghcr.io/withobsrvr/consumer-app:latest
    command:
      - npm
      - start
      - --
      - 409907
      - 409948
    env:
      SOURCE_SERVICE_ADDRESS: ttp-processor:50053
      FLOWCTL_ENDPOINT: localhost:8080
    ports:
      - 3000
    health_check: /health