apiVersion: v1
kind: Pipeline
metadata:
  name: long-running-pipeline
  labels:
    environment: local
    execution: process
spec:
  description: Long-running pipeline to demonstrate monitoring
  sources:
    - id: timer-source
      type: timer-source
      command: ["sh"]
      args: ["-c", "i=1; while [ $i -le 100 ]; do echo \"Timer: $i $(date)\"; i=$((i+1)); sleep 3; done"]
      env:
        SOURCE_ID: "timer-source"
      outputEventTypes:
        - timer.event

  processors:
    - id: counter-processor
      type: counter-processor
      command: ["sh"]
      args: ["-c", "i=1; while read line; do echo \"[$i] $line\"; i=$((i+1)); sleep 1; done"]
      inputs:
        - timer-source
      inputEventTypes:
        - timer.event
      outputEventTypes:
        - counter.event
      env:
        PROCESSOR_ID: "counter-processor"

  sinks:
    - id: logger-sink
      type: logger-sink
      command: ["sh"]
      args: ["-c", "while read line; do echo \"[$(date '+%H:%M:%S')] SINK: $line\"; done"]
      inputs:
        - counter-processor
      inputEventTypes:
        - counter.event
      env:
        SINK_ID: "logger-sink"