apiVersion: flowctl.io/v1alpha1
kind: QuickstartPipeline
metadata:
  name: mainnet-usdc-indexer
  description: Index USDC balances on Stellar mainnet

spec:
  source:
    type: stellar-live-source-datalake
    network: mainnet
    storage:
      type: gcs
      bucket: obsrvr-stellar-ledger-data-pubnet-data
      path: landing/ledgers/pubnet

    ledgers:
      start: 50000000  # Recent mainnet ledger
      end: 51000000    # 1M ledgers

  filters:
    assets:
      - code: USDC
        issuer: GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
        description: "Circle USDC on mainnet"

  processor:
    type: account-balance
    batchSize: 5000

  consumer:
    type: duckdb
    database:
      path: ./mainnet_usdc_balances.duckdb
