apiVersion: v1
kind: Pipeline
metadata:
  name: mock-pipeline
  labels:
    environment: local
    execution: process
spec:
  description: Pipeline using mock components with flowctl integration
  sources:
    - id: mock-source
      type: mock-source
      command: ["./examples/mock-component.sh"]
      env:
        FLOWCTL_SERVICE_TYPE: "source"
      outputEventTypes:
        - mock.event

  processors:
    - id: mock-processor
      type: mock-processor
      command: ["./examples/mock-component.sh"]
      inputs:
        - mock-source
      inputEventTypes:
        - mock.event
      outputEventTypes:
        - mock.processed
      env:
        FLOWCTL_SERVICE_TYPE: "processor"

  sinks:
    - id: mock-sink
      type: mock-sink
      command: ["./examples/mock-component.sh"]
      inputs:
        - mock-processor
      inputEventTypes:
        - mock.processed
      env:
        FLOWCTL_SERVICE_TYPE: "sink"