apiVersion: v1
kind: Pipeline
metadata:
  name: simple-local-pipeline
  labels:
    environment: local
    execution: process
spec:
  description: Simple local pipeline using common Unix commands
  sources:
    - id: date-source
      type: date-source
      command: ["sh"]
      args: ["-c", "while true; do date; sleep 2; done"]
      env:
        SOURCE_ID: "date-source"
        FLOWCTL_SERVICE_TYPE: "source"
      outputEventTypes:
        - timestamp.event
    
    - id: counter-source
      type: counter-source
      command: ["sh"]
      args: ["-c", "i=1; while [ $i -le 20 ]; do echo \"Count: $i\"; i=$((i+1)); sleep 1; done"]
      env:
        SOURCE_ID: "counter-source"
        FLOWCTL_SERVICE_TYPE: "source"
      outputEventTypes:
        - counter.event

  processors:
    - id: prefix-processor
      type: prefix-processor
      command: ["sed"]
      args: ["s/^/[PROCESSED] /"]
      inputs:
        - date-source
        - counter-source
      inputEventTypes:
        - timestamp.event
        - counter.event
      outputEventTypes:
        - processed.event
      env:
        PROCESSOR_ID: "prefix-processor"
        FLOWCTL_SERVICE_TYPE: "processor"

  sinks:
    - id: console-sink
      type: console-sink
      command: ["sh"]
      args: ["-c", "while read line; do echo \"[SINK] $line\"; done"]
      inputs:
        - prefix-processor
      inputEventTypes:
        - processed.event
      env:
        SINK_ID: "console-sink"
        FLOWCTL_SERVICE_TYPE: "sink"