apiVersion: flowctl/v1
kind: Pipeline
metadata:
  name: stellar-token-pipeline
spec:
  description: Pipeline for processing Stellar token transfers
  sources:
    - id: stellar-live-source
      type: source
      image: ghcr.io/withobsrvr/stellar-live-source-datalake:latest
      config:
        network: testnet
  processors:
    - id: ttp-processor
      image: ghcr.io/withobsrvr/ttp-processor:latest
      inputs: [stellar-live-source]
  sinks:
    - id: consumer-app
      image: ghcr.io/withobsrvr/consumer-app:latest
      inputs: [ttp-processor]