apiVersion: v1
kind: Pipeline
metadata:
  name: test-embedded-pipeline
  labels:
    environment: test
spec:
  description: Test pipeline for embedded control plane
  sources:
    - id: test-source
      type: stellar-live-source-datalake
      image: test-source:latest
      outputEventTypes:
        - stellar.transaction
      env:
        TEST_MODE: "true"
        DELAY_SECONDS: "2"
  processors:
    - id: test-processor
      type: ttp-processor
      image: test-processor:latest
      inputs:
        - test-source
      inputEventTypes:
        - stellar.transaction
      outputEventTypes:
        - stellar.processed
      env:
        TEST_MODE: "true"
  sinks:
    - id: test-sink
      type: consumer-app
      image: test-sink:latest
      inputs:
        - test-processor
      inputEventTypes:
        - stellar.processed
      env:
        TEST_MODE: "true"
        OUTPUT_FILE: "test-output.json"