version: 0.1
log_level: info

source:
  type: stellar
  params:
    network: testnet
    cursor: now

processors:
  - name: account_processor
    plugin: account_enrichment
    params:
      include_history: true
      fields:
        - account_id
        - balance
        - sequence

  - name: transaction_processor
    plugin: transaction_filter
    params:
      min_amount: 100
      exclude_types:
        - create_account
      include_types:
        - payment
        - path_payment

sink:
  type: kafka
  params:
    bootstrap_servers: localhost:9092
    topic: enriched-transactions
    batch_size: 100
    compression: gzip

# TLS configuration for secure communication
tls:
  mode: enabled  # enabled for server-side TLS, mutual for mTLS
  cert_file: certs/client.crt
  key_file: certs/client.key
  ca_file: certs/ca.crt
  server_name: flowctl-server.example.com