// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: proto/control_plane.proto

package flowctlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Register_FullMethodName          = "/flowctl.ControlPlane/Register"
	ControlPlane_Heartbeat_FullMethodName         = "/flowctl.ControlPlane/Heartbeat"
	ControlPlane_GetServiceStatus_FullMethodName  = "/flowctl.ControlPlane/GetServiceStatus"
	ControlPlane_ListServices_FullMethodName      = "/flowctl.ControlPlane/ListServices"
	ControlPlane_CreatePipelineRun_FullMethodName = "/flowctl.ControlPlane/CreatePipelineRun"
	ControlPlane_UpdatePipelineRun_FullMethodName = "/flowctl.ControlPlane/UpdatePipelineRun"
	ControlPlane_GetPipelineRun_FullMethodName    = "/flowctl.ControlPlane/GetPipelineRun"
	ControlPlane_ListPipelineRuns_FullMethodName  = "/flowctl.ControlPlane/ListPipelineRuns"
	ControlPlane_StopPipelineRun_FullMethodName   = "/flowctl.ControlPlane/StopPipelineRun"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control plane service definition
type ControlPlaneClient interface {
	// Register a new service with the control plane
	Register(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*RegistrationAck, error)
	// Send periodic heartbeats
	Heartbeat(ctx context.Context, in *ServiceHeartbeat, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get service status
	GetServiceStatus(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*ServiceStatus, error)
	// List all registered services
	ListServices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceList, error)
	// Pipeline run management
	CreatePipelineRun(ctx context.Context, in *CreatePipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error)
	UpdatePipelineRun(ctx context.Context, in *UpdatePipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error)
	GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error)
	ListPipelineRuns(ctx context.Context, in *ListPipelineRunsRequest, opts ...grpc.CallOption) (*ListPipelineRunsResponse, error)
	StopPipelineRun(ctx context.Context, in *StopPipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Register(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*RegistrationAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationAck)
	err := c.cc.Invoke(ctx, ControlPlane_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *ServiceHeartbeat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetServiceStatus(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*ServiceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatus)
	err := c.cc.Invoke(ctx, ControlPlane_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListServices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceList)
	err := c.cc.Invoke(ctx, ControlPlane_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CreatePipelineRun(ctx context.Context, in *CreatePipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineRun)
	err := c.cc.Invoke(ctx, ControlPlane_CreatePipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) UpdatePipelineRun(ctx context.Context, in *UpdatePipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineRun)
	err := c.cc.Invoke(ctx, ControlPlane_UpdatePipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetPipelineRun(ctx context.Context, in *GetPipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineRun)
	err := c.cc.Invoke(ctx, ControlPlane_GetPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListPipelineRuns(ctx context.Context, in *ListPipelineRunsRequest, opts ...grpc.CallOption) (*ListPipelineRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPipelineRunsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListPipelineRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StopPipelineRun(ctx context.Context, in *StopPipelineRunRequest, opts ...grpc.CallOption) (*PipelineRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipelineRun)
	err := c.cc.Invoke(ctx, ControlPlane_StopPipelineRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// Control plane service definition
type ControlPlaneServer interface {
	// Register a new service with the control plane
	Register(context.Context, *ServiceInfo) (*RegistrationAck, error)
	// Send periodic heartbeats
	Heartbeat(context.Context, *ServiceHeartbeat) (*emptypb.Empty, error)
	// Get service status
	GetServiceStatus(context.Context, *ServiceInfo) (*ServiceStatus, error)
	// List all registered services
	ListServices(context.Context, *emptypb.Empty) (*ServiceList, error)
	// Pipeline run management
	CreatePipelineRun(context.Context, *CreatePipelineRunRequest) (*PipelineRun, error)
	UpdatePipelineRun(context.Context, *UpdatePipelineRunRequest) (*PipelineRun, error)
	GetPipelineRun(context.Context, *GetPipelineRunRequest) (*PipelineRun, error)
	ListPipelineRuns(context.Context, *ListPipelineRunsRequest) (*ListPipelineRunsResponse, error)
	StopPipelineRun(context.Context, *StopPipelineRunRequest) (*PipelineRun, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Register(context.Context, *ServiceInfo) (*RegistrationAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *ServiceHeartbeat) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) GetServiceStatus(context.Context, *ServiceInfo) (*ServiceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedControlPlaneServer) ListServices(context.Context, *emptypb.Empty) (*ServiceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedControlPlaneServer) CreatePipelineRun(context.Context, *CreatePipelineRunRequest) (*PipelineRun, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePipelineRun not implemented")
}
func (UnimplementedControlPlaneServer) UpdatePipelineRun(context.Context, *UpdatePipelineRunRequest) (*PipelineRun, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePipelineRun not implemented")
}
func (UnimplementedControlPlaneServer) GetPipelineRun(context.Context, *GetPipelineRunRequest) (*PipelineRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPipelineRun not implemented")
}
func (UnimplementedControlPlaneServer) ListPipelineRuns(context.Context, *ListPipelineRunsRequest) (*ListPipelineRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPipelineRuns not implemented")
}
func (UnimplementedControlPlaneServer) StopPipelineRun(context.Context, *StopPipelineRunRequest) (*PipelineRun, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPipelineRun not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Register(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*ServiceHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetServiceStatus(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListServices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CreatePipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CreatePipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CreatePipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CreatePipelineRun(ctx, req.(*CreatePipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_UpdatePipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).UpdatePipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_UpdatePipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).UpdatePipelineRun(ctx, req.(*UpdatePipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetPipelineRun(ctx, req.(*GetPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListPipelineRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPipelineRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListPipelineRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListPipelineRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListPipelineRuns(ctx, req.(*ListPipelineRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StopPipelineRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPipelineRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).StopPipelineRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_StopPipelineRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).StopPipelineRun(ctx, req.(*StopPipelineRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowctl.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControlPlane_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _ControlPlane_GetServiceStatus_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ControlPlane_ListServices_Handler,
		},
		{
			MethodName: "CreatePipelineRun",
			Handler:    _ControlPlane_CreatePipelineRun_Handler,
		},
		{
			MethodName: "UpdatePipelineRun",
			Handler:    _ControlPlane_UpdatePipelineRun_Handler,
		},
		{
			MethodName: "GetPipelineRun",
			Handler:    _ControlPlane_GetPipelineRun_Handler,
		},
		{
			MethodName: "ListPipelineRuns",
			Handler:    _ControlPlane_ListPipelineRuns_Handler,
		},
		{
			MethodName: "StopPipelineRun",
			Handler:    _ControlPlane_StopPipelineRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control_plane.proto",
}
