// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/control_plane.proto

package flowctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service types that can register with the control plane
type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_SOURCE      ServiceType = 1
	ServiceType_SERVICE_TYPE_PROCESSOR   ServiceType = 2
	ServiceType_SERVICE_TYPE_SINK        ServiceType = 3
	ServiceType_SERVICE_TYPE_PIPELINE    ServiceType = 4 // Composite service containing source, processors, and sinks
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_SOURCE",
		2: "SERVICE_TYPE_PROCESSOR",
		3: "SERVICE_TYPE_SINK",
		4: "SERVICE_TYPE_PIPELINE",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_SOURCE":      1,
		"SERVICE_TYPE_PROCESSOR":   2,
		"SERVICE_TYPE_SINK":        3,
		"SERVICE_TYPE_PIPELINE":    4,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{0}
}

// Pipeline run status
type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNKNOWN   RunStatus = 0
	RunStatus_RUN_STATUS_STARTING  RunStatus = 1
	RunStatus_RUN_STATUS_RUNNING   RunStatus = 2
	RunStatus_RUN_STATUS_COMPLETED RunStatus = 3
	RunStatus_RUN_STATUS_FAILED    RunStatus = 4
	RunStatus_RUN_STATUS_STOPPED   RunStatus = 5
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNKNOWN",
		1: "RUN_STATUS_STARTING",
		2: "RUN_STATUS_RUNNING",
		3: "RUN_STATUS_COMPLETED",
		4: "RUN_STATUS_FAILED",
		5: "RUN_STATUS_STOPPED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNKNOWN":   0,
		"RUN_STATUS_STARTING":  1,
		"RUN_STATUS_RUNNING":   2,
		"RUN_STATUS_COMPLETED": 3,
		"RUN_STATUS_FAILED":    4,
		"RUN_STATUS_STOPPED":   5,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[1].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[1]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{1}
}

// Historical chunk lifecycle status.
type ChunkStatus int32

const (
	ChunkStatus_CHUNK_STATUS_UNKNOWN       ChunkStatus = 0
	ChunkStatus_CHUNK_STATUS_PLANNED       ChunkStatus = 1
	ChunkStatus_CHUNK_STATUS_DISPATCHED    ChunkStatus = 2
	ChunkStatus_CHUNK_STATUS_RUNNING       ChunkStatus = 3
	ChunkStatus_CHUNK_STATUS_COMPLETED     ChunkStatus = 4
	ChunkStatus_CHUNK_STATUS_VERIFIED      ChunkStatus = 5
	ChunkStatus_CHUNK_STATUS_FAILED        ChunkStatus = 6
	ChunkStatus_CHUNK_STATUS_RETRY_PENDING ChunkStatus = 7
	ChunkStatus_CHUNK_STATUS_ABORTED       ChunkStatus = 8
)

// Enum value maps for ChunkStatus.
var (
	ChunkStatus_name = map[int32]string{
		0: "CHUNK_STATUS_UNKNOWN",
		1: "CHUNK_STATUS_PLANNED",
		2: "CHUNK_STATUS_DISPATCHED",
		3: "CHUNK_STATUS_RUNNING",
		4: "CHUNK_STATUS_COMPLETED",
		5: "CHUNK_STATUS_VERIFIED",
		6: "CHUNK_STATUS_FAILED",
		7: "CHUNK_STATUS_RETRY_PENDING",
		8: "CHUNK_STATUS_ABORTED",
	}
	ChunkStatus_value = map[string]int32{
		"CHUNK_STATUS_UNKNOWN":       0,
		"CHUNK_STATUS_PLANNED":       1,
		"CHUNK_STATUS_DISPATCHED":    2,
		"CHUNK_STATUS_RUNNING":       3,
		"CHUNK_STATUS_COMPLETED":     4,
		"CHUNK_STATUS_VERIFIED":      5,
		"CHUNK_STATUS_FAILED":        6,
		"CHUNK_STATUS_RETRY_PENDING": 7,
		"CHUNK_STATUS_ABORTED":       8,
	}
)

func (x ChunkStatus) Enum() *ChunkStatus {
	p := new(ChunkStatus)
	*p = x
	return p
}

func (x ChunkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChunkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[2].Descriptor()
}

func (ChunkStatus) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[2]
}

func (x ChunkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChunkStatus.Descriptor instead.
func (ChunkStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{2}
}

// Typed failure class reported by data-plane components.
type FailureClass int32

const (
	FailureClass_FAILURE_CLASS_UNKNOWN                  FailureClass = 0
	FailureClass_FAILURE_CLASS_RETRYABLE_INFRASTRUCTURE FailureClass = 1
	FailureClass_FAILURE_CLASS_NON_RETRYABLE_DATA       FailureClass = 2
	FailureClass_FAILURE_CLASS_NON_RETRYABLE_SCHEMA     FailureClass = 3
	FailureClass_FAILURE_CLASS_VERIFICATION             FailureClass = 4
	FailureClass_FAILURE_CLASS_ALLOCATION_LOST          FailureClass = 5
	FailureClass_FAILURE_CLASS_OOM                      FailureClass = 6
)

// Enum value maps for FailureClass.
var (
	FailureClass_name = map[int32]string{
		0: "FAILURE_CLASS_UNKNOWN",
		1: "FAILURE_CLASS_RETRYABLE_INFRASTRUCTURE",
		2: "FAILURE_CLASS_NON_RETRYABLE_DATA",
		3: "FAILURE_CLASS_NON_RETRYABLE_SCHEMA",
		4: "FAILURE_CLASS_VERIFICATION",
		5: "FAILURE_CLASS_ALLOCATION_LOST",
		6: "FAILURE_CLASS_OOM",
	}
	FailureClass_value = map[string]int32{
		"FAILURE_CLASS_UNKNOWN":                  0,
		"FAILURE_CLASS_RETRYABLE_INFRASTRUCTURE": 1,
		"FAILURE_CLASS_NON_RETRYABLE_DATA":       2,
		"FAILURE_CLASS_NON_RETRYABLE_SCHEMA":     3,
		"FAILURE_CLASS_VERIFICATION":             4,
		"FAILURE_CLASS_ALLOCATION_LOST":          5,
		"FAILURE_CLASS_OOM":                      6,
	}
)

func (x FailureClass) Enum() *FailureClass {
	p := new(FailureClass)
	*p = x
	return p
}

func (x FailureClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[3].Descriptor()
}

func (FailureClass) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[3]
}

func (x FailureClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureClass.Descriptor instead.
func (FailureClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{3}
}

// Service registration information
type ServiceInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceId        string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceType      ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=flowctl.ServiceType" json:"service_type,omitempty"`
	InputEventTypes  []string               `protobuf:"bytes,3,rep,name=input_event_types,json=inputEventTypes,proto3" json:"input_event_types,omitempty"`                                    // For processors only
	OutputEventTypes []string               `protobuf:"bytes,4,rep,name=output_event_types,json=outputEventTypes,proto3" json:"output_event_types,omitempty"`                                 // For sources and processors
	HealthEndpoint   string                 `protobuf:"bytes,5,opt,name=health_endpoint,json=healthEndpoint,proto3" json:"health_endpoint,omitempty"`                                         // Prometheus metrics endpoint
	MaxInflight      int32                  `protobuf:"varint,6,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`                                                 // Back-pressure credits
	Metadata         map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional service metadata
	ComponentId      string                 `protobuf:"bytes,8,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`                                                  // Component ID from pipeline YAML (e.g., "stellar-source")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceInfo) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceInfo) GetInputEventTypes() []string {
	if x != nil {
		return x.InputEventTypes
	}
	return nil
}

func (x *ServiceInfo) GetOutputEventTypes() []string {
	if x != nil {
		return x.OutputEventTypes
	}
	return nil
}

func (x *ServiceInfo) GetHealthEndpoint() string {
	if x != nil {
		return x.HealthEndpoint
	}
	return ""
}

func (x *ServiceInfo) GetMaxInflight() int32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInfo) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

// Registration acknowledgment
type RegistrationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TopicNames     []string               `protobuf:"bytes,2,rep,name=topic_names,json=topicNames,proto3" json:"topic_names,omitempty"`                                                                                       // Kafka topics to consume/produce
	ConnectionInfo map[string]string      `protobuf:"bytes,3,rep,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Connection details (endpoints, creds)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_proto_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationAck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegistrationAck) GetTopicNames() []string {
	if x != nil {
		return x.TopicNames
	}
	return nil
}

func (x *RegistrationAck) GetConnectionInfo() map[string]string {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

// ServiceHeartbeat message
type ServiceHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Service-specific metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeat) Reset() {
	*x = ServiceHeartbeat{}
	mi := &file_proto_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeat) ProtoMessage() {}

func (x *ServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceHeartbeat) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceHeartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServiceHeartbeat) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Service status information
type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=flowctl.ServiceType" json:"service_type,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,3,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ComponentId   string                 `protobuf:"bytes,6,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"` // Component ID from pipeline YAML
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_proto_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceStatus) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *ServiceStatus) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *ServiceStatus) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ServiceStatus) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

// List of registered services
type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceStatus       `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_proto_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceList) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

// Metrics for a pipeline run
type RunMetrics struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	EventsProcessed  int64                        `protobuf:"varint,1,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	EventsPerSecond  float64                      `protobuf:"fixed64,2,opt,name=events_per_second,json=eventsPerSecond,proto3" json:"events_per_second,omitempty"`
	BytesProcessed   int64                        `protobuf:"varint,3,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	ComponentMetrics map[string]*ComponentMetrics `protobuf:"bytes,4,rep,name=component_metrics,json=componentMetrics,proto3" json:"component_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunMetrics) Reset() {
	*x = RunMetrics{}
	mi := &file_proto_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetrics) ProtoMessage() {}

func (x *RunMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetrics.ProtoReflect.Descriptor instead.
func (*RunMetrics) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *RunMetrics) GetEventsProcessed() int64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *RunMetrics) GetEventsPerSecond() float64 {
	if x != nil {
		return x.EventsPerSecond
	}
	return 0
}

func (x *RunMetrics) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *RunMetrics) GetComponentMetrics() map[string]*ComponentMetrics {
	if x != nil {
		return x.ComponentMetrics
	}
	return nil
}

// Per-component metrics
type ComponentMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventsIn         int64                  `protobuf:"varint,1,opt,name=events_in,json=eventsIn,proto3" json:"events_in,omitempty"`
	EventsOut        int64                  `protobuf:"varint,2,opt,name=events_out,json=eventsOut,proto3" json:"events_out,omitempty"`
	BytesIn          int64                  `protobuf:"varint,3,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut         int64                  `protobuf:"varint,4,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ProcessingTimeMs float64                `protobuf:"fixed64,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComponentMetrics) Reset() {
	*x = ComponentMetrics{}
	mi := &file_proto_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMetrics) ProtoMessage() {}

func (x *ComponentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMetrics.ProtoReflect.Descriptor instead.
func (*ComponentMetrics) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentMetrics) GetEventsIn() int64 {
	if x != nil {
		return x.EventsIn
	}
	return 0
}

func (x *ComponentMetrics) GetEventsOut() int64 {
	if x != nil {
		return x.EventsOut
	}
	return 0
}

func (x *ComponentMetrics) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *ComponentMetrics) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *ComponentMetrics) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Pipeline run record
type PipelineRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineName  string                 `protobuf:"bytes,3,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	Status        RunStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ConfigYaml    string                 `protobuf:"bytes,7,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	Metrics       *RunMetrics            `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	ComponentIds  []string               `protobuf:"bytes,10,rep,name=component_ids,json=componentIds,proto3" json:"component_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRun) Reset() {
	*x = PipelineRun{}
	mi := &file_proto_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRun) ProtoMessage() {}

func (x *PipelineRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRun.ProtoReflect.Descriptor instead.
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PipelineRun) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineRun) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *PipelineRun) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *PipelineRun) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PipelineRun) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *PipelineRun) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *PipelineRun) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PipelineRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PipelineRun) GetComponentIds() []string {
	if x != nil {
		return x.ComponentIds
	}
	return nil
}

// Create pipeline run request
type CreatePipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PipelineName  string                 `protobuf:"bytes,2,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	ConfigYaml    string                 `protobuf:"bytes,3,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	ComponentIds  []string               `protobuf:"bytes,4,rep,name=component_ids,json=componentIds,proto3" json:"component_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRunRequest) Reset() {
	*x = CreatePipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRunRequest) ProtoMessage() {}

func (x *CreatePipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRunRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetComponentIds() []string {
	if x != nil {
		return x.ComponentIds
	}
	return nil
}

// Update pipeline run request
type UpdatePipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        RunStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`
	Metrics       *RunMetrics            `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineRunRequest) Reset() {
	*x = UpdatePipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineRunRequest) ProtoMessage() {}

func (x *UpdatePipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineRunRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *UpdatePipelineRunRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *UpdatePipelineRunRequest) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *UpdatePipelineRunRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get pipeline run request
type GetPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunRequest) Reset() {
	*x = GetPipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunRequest) ProtoMessage() {}

func (x *GetPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *GetPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// List pipeline runs request
type ListPipelineRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineName  string                 `protobuf:"bytes,1,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"` // Optional: filter by pipeline name
	Status        RunStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`         // Optional: filter by status
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Optional: limit number of results (default: 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsRequest) Reset() {
	*x = ListPipelineRunsRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsRequest) ProtoMessage() {}

func (x *ListPipelineRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *ListPipelineRunsRequest) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *ListPipelineRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// List pipeline runs response
type ListPipelineRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*PipelineRun         `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsResponse) Reset() {
	*x = ListPipelineRunsResponse{}
	mi := &file_proto_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsResponse) ProtoMessage() {}

func (x *ListPipelineRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *ListPipelineRunsResponse) GetRuns() []*PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

// Stop pipeline run request
type StopPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPipelineRunRequest) Reset() {
	*x = StopPipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPipelineRunRequest) ProtoMessage() {}

func (x *StopPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*StopPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *StopPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// Historical chunk run record.
type ChunkRun struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChunkId           string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	PipelineRunId     string                 `protobuf:"bytes,2,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	ComponentId       string                 `protobuf:"bytes,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	ChunkStart        int64                  `protobuf:"varint,4,opt,name=chunk_start,json=chunkStart,proto3" json:"chunk_start,omitempty"`
	ChunkEnd          int64                  `protobuf:"varint,5,opt,name=chunk_end,json=chunkEnd,proto3" json:"chunk_end,omitempty"`
	Attempt           int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status            ChunkStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=flowctl.ChunkStatus" json:"status,omitempty"`
	FailureClass      FailureClass           `protobuf:"varint,8,opt,name=failure_class,json=failureClass,proto3,enum=flowctl.FailureClass" json:"failure_class,omitempty"`
	Phase             string                 `protobuf:"bytes,9,opt,name=phase,proto3" json:"phase,omitempty"`
	Error             string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	RecommendedAction string                 `protobuf:"bytes,11,opt,name=recommended_action,json=recommendedAction,proto3" json:"recommended_action,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	VerifiedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	RowCounts         map[string]int64       `protobuf:"bytes,15,rep,name=row_counts,json=rowCounts,proto3" json:"row_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Verification      map[string]string      `protobuf:"bytes,16,rep,name=verification,proto3" json:"verification,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata          map[string]string      `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChunkRun) Reset() {
	*x = ChunkRun{}
	mi := &file_proto_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRun) ProtoMessage() {}

func (x *ChunkRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRun.ProtoReflect.Descriptor instead.
func (*ChunkRun) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *ChunkRun) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkRun) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

func (x *ChunkRun) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ChunkRun) GetChunkStart() int64 {
	if x != nil {
		return x.ChunkStart
	}
	return 0
}

func (x *ChunkRun) GetChunkEnd() int64 {
	if x != nil {
		return x.ChunkEnd
	}
	return 0
}

func (x *ChunkRun) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ChunkRun) GetStatus() ChunkStatus {
	if x != nil {
		return x.Status
	}
	return ChunkStatus_CHUNK_STATUS_UNKNOWN
}

func (x *ChunkRun) GetFailureClass() FailureClass {
	if x != nil {
		return x.FailureClass
	}
	return FailureClass_FAILURE_CLASS_UNKNOWN
}

func (x *ChunkRun) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ChunkRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChunkRun) GetRecommendedAction() string {
	if x != nil {
		return x.RecommendedAction
	}
	return ""
}

func (x *ChunkRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ChunkRun) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ChunkRun) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *ChunkRun) GetRowCounts() map[string]int64 {
	if x != nil {
		return x.RowCounts
	}
	return nil
}

func (x *ChunkRun) GetVerification() map[string]string {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *ChunkRun) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Upsert chunk run request.
type UpsertChunkRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *ChunkRun              `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertChunkRunRequest) Reset() {
	*x = UpsertChunkRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertChunkRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertChunkRunRequest) ProtoMessage() {}

func (x *UpsertChunkRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertChunkRunRequest.ProtoReflect.Descriptor instead.
func (*UpsertChunkRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *UpsertChunkRunRequest) GetChunk() *ChunkRun {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Get chunk run request.
type GetChunkRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRunRequest) Reset() {
	*x = GetChunkRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRunRequest) ProtoMessage() {}

func (x *GetChunkRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRunRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *GetChunkRunRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

// List chunk runs request.
type ListChunkRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineRunId string                 `protobuf:"bytes,1,opt,name=pipeline_run_id,json=pipelineRunId,proto3" json:"pipeline_run_id,omitempty"`
	ComponentId   string                 `protobuf:"bytes,2,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Status        ChunkStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=flowctl.ChunkStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunkRunsRequest) Reset() {
	*x = ListChunkRunsRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunkRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunkRunsRequest) ProtoMessage() {}

func (x *ListChunkRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunkRunsRequest.ProtoReflect.Descriptor instead.
func (*ListChunkRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *ListChunkRunsRequest) GetPipelineRunId() string {
	if x != nil {
		return x.PipelineRunId
	}
	return ""
}

func (x *ListChunkRunsRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ListChunkRunsRequest) GetStatus() ChunkStatus {
	if x != nil {
		return x.Status
	}
	return ChunkStatus_CHUNK_STATUS_UNKNOWN
}

func (x *ListChunkRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// List chunk runs response.
type ListChunkRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkRun            `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunkRunsResponse) Reset() {
	*x = ListChunkRunsResponse{}
	mi := &file_proto_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunkRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunkRunsResponse) ProtoMessage() {}

func (x *ListChunkRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunkRunsResponse.ProtoReflect.Descriptor instead.
func (*ListChunkRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *ListChunkRunsResponse) GetChunks() []*ChunkRun {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_proto_control_plane_proto protoreflect.FileDescriptor

const file_proto_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x19proto/control_plane.proto\x12\aflowctl\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n" +
	"\vServiceInfo\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.flowctl.ServiceTypeR\vserviceType\x12*\n" +
	"\x11input_event_types\x18\x03 \x03(\tR\x0finputEventTypes\x12,\n" +
	"\x12output_event_types\x18\x04 \x03(\tR\x10outputEventTypes\x12'\n" +
	"\x0fhealth_endpoint\x18\x05 \x01(\tR\x0ehealthEndpoint\x12!\n" +
	"\fmax_inflight\x18\x06 \x01(\x05R\vmaxInflight\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".flowctl.ServiceInfo.MetadataEntryR\bmetadata\x12!\n" +
	"\fcomponent_id\x18\b \x01(\tR\vcomponentId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x0fRegistrationAck\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vtopic_names\x18\x02 \x03(\tR\n" +
	"topicNames\x12U\n" +
	"\x0fconnection_info\x18\x03 \x03(\v2,.flowctl.RegistrationAck.ConnectionInfoEntryR\x0econnectionInfo\x1aA\n" +
	"\x13ConnectionInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x10ServiceHeartbeat\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\ametrics\x18\x03 \x03(\v2&.flowctl.ServiceHeartbeat.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe7\x02\n" +
	"\rServiceStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.flowctl.ServiceTypeR\vserviceType\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x03 \x01(\bR\tisHealthy\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12=\n" +
	"\ametrics\x18\x05 \x03(\v2#.flowctl.ServiceStatus.MetricsEntryR\ametrics\x12!\n" +
	"\fcomponent_id\x18\x06 \x01(\tR\vcomponentId\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"A\n" +
	"\vServiceList\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.flowctl.ServiceStatusR\bservices\"\xc4\x02\n" +
	"\n" +
	"RunMetrics\x12)\n" +
	"\x10events_processed\x18\x01 \x01(\x03R\x0feventsProcessed\x12*\n" +
	"\x11events_per_second\x18\x02 \x01(\x01R\x0feventsPerSecond\x12'\n" +
	"\x0fbytes_processed\x18\x03 \x01(\x03R\x0ebytesProcessed\x12V\n" +
	"\x11component_metrics\x18\x04 \x03(\v2).flowctl.RunMetrics.ComponentMetricsEntryR\x10componentMetrics\x1a^\n" +
	"\x15ComponentMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.flowctl.ComponentMetricsR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x10ComponentMetrics\x12\x1b\n" +
	"\tevents_in\x18\x01 \x01(\x03R\beventsIn\x12\x1d\n" +
	"\n" +
	"events_out\x18\x02 \x01(\x03R\teventsOut\x12\x19\n" +
	"\bbytes_in\x18\x03 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x04 \x01(\x03R\bbytesOut\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x01R\x10processingTimeMs\"\x93\x03\n" +
	"\vPipelineRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12#\n" +
	"\rpipeline_name\x18\x03 \x01(\tR\fpipelineName\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vconfig_yaml\x18\a \x01(\tR\n" +
	"configYaml\x12-\n" +
	"\ametrics\x18\b \x01(\v2\x13.flowctl.RunMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12#\n" +
	"\rcomponent_ids\x18\n" +
	" \x03(\tR\fcomponentIds\"\x9c\x01\n" +
	"\x18CreatePipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rpipeline_name\x18\x02 \x01(\tR\fpipelineName\x12\x1f\n" +
	"\vconfig_yaml\x18\x03 \x01(\tR\n" +
	"configYaml\x12#\n" +
	"\rcomponent_ids\x18\x04 \x03(\tR\fcomponentIds\"\xa2\x01\n" +
	"\x18UpdatePipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x12-\n" +
	"\ametrics\x18\x03 \x01(\v2\x13.flowctl.RunMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\".\n" +
	"\x15GetPipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x80\x01\n" +
	"\x17ListPipelineRunsRequest\x12#\n" +
	"\rpipeline_name\x18\x01 \x01(\tR\fpipelineName\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"D\n" +
	"\x18ListPipelineRunsResponse\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.flowctl.PipelineRunR\x04runs\"/\n" +
	"\x16StopPipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xc7\a\n" +
	"\bChunkRun\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12&\n" +
	"\x0fpipeline_run_id\x18\x02 \x01(\tR\rpipelineRunId\x12!\n" +
	"\fcomponent_id\x18\x03 \x01(\tR\vcomponentId\x12\x1f\n" +
	"\vchunk_start\x18\x04 \x01(\x03R\n" +
	"chunkStart\x12\x1b\n" +
	"\tchunk_end\x18\x05 \x01(\x03R\bchunkEnd\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.flowctl.ChunkStatusR\x06status\x12:\n" +
	"\rfailure_class\x18\b \x01(\x0e2\x15.flowctl.FailureClassR\ffailureClass\x12\x14\n" +
	"\x05phase\x18\t \x01(\tR\x05phase\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12-\n" +
	"\x12recommended_action\x18\v \x01(\tR\x11recommendedAction\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12;\n" +
	"\vverified_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12?\n" +
	"\n" +
	"row_counts\x18\x0f \x03(\v2 .flowctl.ChunkRun.RowCountsEntryR\trowCounts\x12G\n" +
	"\fverification\x18\x10 \x03(\v2#.flowctl.ChunkRun.VerificationEntryR\fverification\x12;\n" +
	"\bmetadata\x18\x11 \x03(\v2\x1f.flowctl.ChunkRun.MetadataEntryR\bmetadata\x1a<\n" +
	"\x0eRowCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11VerificationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x15UpsertChunkRunRequest\x12'\n" +
	"\x05chunk\x18\x01 \x01(\v2\x11.flowctl.ChunkRunR\x05chunk\"/\n" +
	"\x12GetChunkRunRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\"\xa5\x01\n" +
	"\x14ListChunkRunsRequest\x12&\n" +
	"\x0fpipeline_run_id\x18\x01 \x01(\tR\rpipelineRunId\x12!\n" +
	"\fcomponent_id\x18\x02 \x01(\tR\vcomponentId\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.flowctl.ChunkStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"B\n" +
	"\x15ListChunkRunsResponse\x12)\n" +
	"\x06chunks\x18\x01 \x03(\v2\x11.flowctl.ChunkRunR\x06chunks*\x92\x01\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVICE_TYPE_SOURCE\x10\x01\x12\x1a\n" +
	"\x16SERVICE_TYPE_PROCESSOR\x10\x02\x12\x15\n" +
	"\x11SERVICE_TYPE_SINK\x10\x03\x12\x19\n" +
	"\x15SERVICE_TYPE_PIPELINE\x10\x04*\x9d\x01\n" +
	"\tRunStatus\x12\x16\n" +
	"\x12RUN_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13RUN_STATUS_STARTING\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x04\x12\x16\n" +
	"\x12RUN_STATUS_STOPPED\x10\x05*\x82\x02\n" +
	"\vChunkStatus\x12\x18\n" +
	"\x14CHUNK_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CHUNK_STATUS_PLANNED\x10\x01\x12\x1b\n" +
	"\x17CHUNK_STATUS_DISPATCHED\x10\x02\x12\x18\n" +
	"\x14CHUNK_STATUS_RUNNING\x10\x03\x12\x1a\n" +
	"\x16CHUNK_STATUS_COMPLETED\x10\x04\x12\x19\n" +
	"\x15CHUNK_STATUS_VERIFIED\x10\x05\x12\x17\n" +
	"\x13CHUNK_STATUS_FAILED\x10\x06\x12\x1e\n" +
	"\x1aCHUNK_STATUS_RETRY_PENDING\x10\a\x12\x18\n" +
	"\x14CHUNK_STATUS_ABORTED\x10\b*\xfd\x01\n" +
	"\fFailureClass\x12\x19\n" +
	"\x15FAILURE_CLASS_UNKNOWN\x10\x00\x12*\n" +
	"&FAILURE_CLASS_RETRYABLE_INFRASTRUCTURE\x10\x01\x12$\n" +
	" FAILURE_CLASS_NON_RETRYABLE_DATA\x10\x02\x12&\n" +
	"\"FAILURE_CLASS_NON_RETRYABLE_SCHEMA\x10\x03\x12\x1e\n" +
	"\x1aFAILURE_CLASS_VERIFICATION\x10\x04\x12!\n" +
	"\x1dFAILURE_CLASS_ALLOCATION_LOST\x10\x05\x12\x15\n" +
	"\x11FAILURE_CLASS_OOM\x10\x062\xe5\x06\n" +
	"\fControlPlane\x12:\n" +
	"\bRegister\x12\x14.flowctl.ServiceInfo\x1a\x18.flowctl.RegistrationAck\x12>\n" +
	"\tHeartbeat\x12\x19.flowctl.ServiceHeartbeat\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x10GetServiceStatus\x12\x14.flowctl.ServiceInfo\x1a\x16.flowctl.ServiceStatus\x12<\n" +
	"\fListServices\x12\x16.google.protobuf.Empty\x1a\x14.flowctl.ServiceList\x12L\n" +
	"\x11CreatePipelineRun\x12!.flowctl.CreatePipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12L\n" +
	"\x11UpdatePipelineRun\x12!.flowctl.UpdatePipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12F\n" +
	"\x0eGetPipelineRun\x12\x1e.flowctl.GetPipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12W\n" +
	"\x10ListPipelineRuns\x12 .flowctl.ListPipelineRunsRequest\x1a!.flowctl.ListPipelineRunsResponse\x12H\n" +
	"\x0fStopPipelineRun\x12\x1f.flowctl.StopPipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12C\n" +
	"\x0eUpsertChunkRun\x12\x1e.flowctl.UpsertChunkRunRequest\x1a\x11.flowctl.ChunkRun\x12=\n" +
	"\vGetChunkRun\x12\x1b.flowctl.GetChunkRunRequest\x1a\x11.flowctl.ChunkRun\x12N\n" +
	"\rListChunkRuns\x12\x1d.flowctl.ListChunkRunsRequest\x1a\x1e.flowctl.ListChunkRunsResponseB/Z-github.com/withobsrvr/flowctl/proto;flowctlpbb\x06proto3"

var (
	file_proto_control_plane_proto_rawDescOnce sync.Once
	file_proto_control_plane_proto_rawDescData []byte
)

func file_proto_control_plane_proto_rawDescGZIP() []byte {
	file_proto_control_plane_proto_rawDescOnce.Do(func() {
		file_proto_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_plane_proto_rawDesc), len(file_proto_control_plane_proto_rawDesc)))
	})
	return file_proto_control_plane_proto_rawDescData
}

var file_proto_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_control_plane_proto_goTypes = []any{
	(ServiceType)(0),                 // 0: flowctl.ServiceType
	(RunStatus)(0),                   // 1: flowctl.RunStatus
	(ChunkStatus)(0),                 // 2: flowctl.ChunkStatus
	(FailureClass)(0),                // 3: flowctl.FailureClass
	(*ServiceInfo)(nil),              // 4: flowctl.ServiceInfo
	(*RegistrationAck)(nil),          // 5: flowctl.RegistrationAck
	(*ServiceHeartbeat)(nil),         // 6: flowctl.ServiceHeartbeat
	(*ServiceStatus)(nil),            // 7: flowctl.ServiceStatus
	(*ServiceList)(nil),              // 8: flowctl.ServiceList
	(*RunMetrics)(nil),               // 9: flowctl.RunMetrics
	(*ComponentMetrics)(nil),         // 10: flowctl.ComponentMetrics
	(*PipelineRun)(nil),              // 11: flowctl.PipelineRun
	(*CreatePipelineRunRequest)(nil), // 12: flowctl.CreatePipelineRunRequest
	(*UpdatePipelineRunRequest)(nil), // 13: flowctl.UpdatePipelineRunRequest
	(*GetPipelineRunRequest)(nil),    // 14: flowctl.GetPipelineRunRequest
	(*ListPipelineRunsRequest)(nil),  // 15: flowctl.ListPipelineRunsRequest
	(*ListPipelineRunsResponse)(nil), // 16: flowctl.ListPipelineRunsResponse
	(*StopPipelineRunRequest)(nil),   // 17: flowctl.StopPipelineRunRequest
	(*ChunkRun)(nil),                 // 18: flowctl.ChunkRun
	(*UpsertChunkRunRequest)(nil),    // 19: flowctl.UpsertChunkRunRequest
	(*GetChunkRunRequest)(nil),       // 20: flowctl.GetChunkRunRequest
	(*ListChunkRunsRequest)(nil),     // 21: flowctl.ListChunkRunsRequest
	(*ListChunkRunsResponse)(nil),    // 22: flowctl.ListChunkRunsResponse
	nil,                              // 23: flowctl.ServiceInfo.MetadataEntry
	nil,                              // 24: flowctl.RegistrationAck.ConnectionInfoEntry
	nil,                              // 25: flowctl.ServiceHeartbeat.MetricsEntry
	nil,                              // 26: flowctl.ServiceStatus.MetricsEntry
	nil,                              // 27: flowctl.RunMetrics.ComponentMetricsEntry
	nil,                              // 28: flowctl.ChunkRun.RowCountsEntry
	nil,                              // 29: flowctl.ChunkRun.VerificationEntry
	nil,                              // 30: flowctl.ChunkRun.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 32: google.protobuf.Empty
}
var file_proto_control_plane_proto_depIdxs = []int32{
	0,  // 0: flowctl.ServiceInfo.service_type:type_name -> flowctl.ServiceType
	23, // 1: flowctl.ServiceInfo.metadata:type_name -> flowctl.ServiceInfo.MetadataEntry
	24, // 2: flowctl.RegistrationAck.connection_info:type_name -> flowctl.RegistrationAck.ConnectionInfoEntry
	31, // 3: flowctl.ServiceHeartbeat.timestamp:type_name -> google.protobuf.Timestamp
	25, // 4: flowctl.ServiceHeartbeat.metrics:type_name -> flowctl.ServiceHeartbeat.MetricsEntry
	0,  // 5: flowctl.ServiceStatus.service_type:type_name -> flowctl.ServiceType
	31, // 6: flowctl.ServiceStatus.last_heartbeat:type_name -> google.protobuf.Timestamp
	26, // 7: flowctl.ServiceStatus.metrics:type_name -> flowctl.ServiceStatus.MetricsEntry
	7,  // 8: flowctl.ServiceList.services:type_name -> flowctl.ServiceStatus
	27, // 9: flowctl.RunMetrics.component_metrics:type_name -> flowctl.RunMetrics.ComponentMetricsEntry
	1,  // 10: flowctl.PipelineRun.status:type_name -> flowctl.RunStatus
	31, // 11: flowctl.PipelineRun.start_time:type_name -> google.protobuf.Timestamp
	31, // 12: flowctl.PipelineRun.end_time:type_name -> google.protobuf.Timestamp
	9,  // 13: flowctl.PipelineRun.metrics:type_name -> flowctl.RunMetrics
	1,  // 14: flowctl.UpdatePipelineRunRequest.status:type_name -> flowctl.RunStatus
	9,  // 15: flowctl.UpdatePipelineRunRequest.metrics:type_name -> flowctl.RunMetrics
	1,  // 16: flowctl.ListPipelineRunsRequest.status:type_name -> flowctl.RunStatus
	11, // 17: flowctl.ListPipelineRunsResponse.runs:type_name -> flowctl.PipelineRun
	2,  // 18: flowctl.ChunkRun.status:type_name -> flowctl.ChunkStatus
	3,  // 19: flowctl.ChunkRun.failure_class:type_name -> flowctl.FailureClass
	31, // 20: flowctl.ChunkRun.started_at:type_name -> google.protobuf.Timestamp
	31, // 21: flowctl.ChunkRun.completed_at:type_name -> google.protobuf.Timestamp
	31, // 22: flowctl.ChunkRun.verified_at:type_name -> google.protobuf.Timestamp
	28, // 23: flowctl.ChunkRun.row_counts:type_name -> flowctl.ChunkRun.RowCountsEntry
	29, // 24: flowctl.ChunkRun.verification:type_name -> flowctl.ChunkRun.VerificationEntry
	30, // 25: flowctl.ChunkRun.metadata:type_name -> flowctl.ChunkRun.MetadataEntry
	18, // 26: flowctl.UpsertChunkRunRequest.chunk:type_name -> flowctl.ChunkRun
	2,  // 27: flowctl.ListChunkRunsRequest.status:type_name -> flowctl.ChunkStatus
	18, // 28: flowctl.ListChunkRunsResponse.chunks:type_name -> flowctl.ChunkRun
	10, // 29: flowctl.RunMetrics.ComponentMetricsEntry.value:type_name -> flowctl.ComponentMetrics
	4,  // 30: flowctl.ControlPlane.Register:input_type -> flowctl.ServiceInfo
	6,  // 31: flowctl.ControlPlane.Heartbeat:input_type -> flowctl.ServiceHeartbeat
	4,  // 32: flowctl.ControlPlane.GetServiceStatus:input_type -> flowctl.ServiceInfo
	32, // 33: flowctl.ControlPlane.ListServices:input_type -> google.protobuf.Empty
	12, // 34: flowctl.ControlPlane.CreatePipelineRun:input_type -> flowctl.CreatePipelineRunRequest
	13, // 35: flowctl.ControlPlane.UpdatePipelineRun:input_type -> flowctl.UpdatePipelineRunRequest
	14, // 36: flowctl.ControlPlane.GetPipelineRun:input_type -> flowctl.GetPipelineRunRequest
	15, // 37: flowctl.ControlPlane.ListPipelineRuns:input_type -> flowctl.ListPipelineRunsRequest
	17, // 38: flowctl.ControlPlane.StopPipelineRun:input_type -> flowctl.StopPipelineRunRequest
	19, // 39: flowctl.ControlPlane.UpsertChunkRun:input_type -> flowctl.UpsertChunkRunRequest
	20, // 40: flowctl.ControlPlane.GetChunkRun:input_type -> flowctl.GetChunkRunRequest
	21, // 41: flowctl.ControlPlane.ListChunkRuns:input_type -> flowctl.ListChunkRunsRequest
	5,  // 42: flowctl.ControlPlane.Register:output_type -> flowctl.RegistrationAck
	32, // 43: flowctl.ControlPlane.Heartbeat:output_type -> google.protobuf.Empty
	7,  // 44: flowctl.ControlPlane.GetServiceStatus:output_type -> flowctl.ServiceStatus
	8,  // 45: flowctl.ControlPlane.ListServices:output_type -> flowctl.ServiceList
	11, // 46: flowctl.ControlPlane.CreatePipelineRun:output_type -> flowctl.PipelineRun
	11, // 47: flowctl.ControlPlane.UpdatePipelineRun:output_type -> flowctl.PipelineRun
	11, // 48: flowctl.ControlPlane.GetPipelineRun:output_type -> flowctl.PipelineRun
	16, // 49: flowctl.ControlPlane.ListPipelineRuns:output_type -> flowctl.ListPipelineRunsResponse
	11, // 50: flowctl.ControlPlane.StopPipelineRun:output_type -> flowctl.PipelineRun
	18, // 51: flowctl.ControlPlane.UpsertChunkRun:output_type -> flowctl.ChunkRun
	18, // 52: flowctl.ControlPlane.GetChunkRun:output_type -> flowctl.ChunkRun
	22, // 53: flowctl.ControlPlane.ListChunkRuns:output_type -> flowctl.ListChunkRunsResponse
	42, // [42:54] is the sub-list for method output_type
	30, // [30:42] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_control_plane_proto_init() }
func file_proto_control_plane_proto_init() {
	if File_proto_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_plane_proto_rawDesc), len(file_proto_control_plane_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_plane_proto_goTypes,
		DependencyIndexes: file_proto_control_plane_proto_depIdxs,
		EnumInfos:         file_proto_control_plane_proto_enumTypes,
		MessageInfos:      file_proto_control_plane_proto_msgTypes,
	}.Build()
	File_proto_control_plane_proto = out.File
	file_proto_control_plane_proto_goTypes = nil
	file_proto_control_plane_proto_depIdxs = nil
}
