// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/control_plane.proto

package flowctlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service types that can register with the control plane
type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_SOURCE      ServiceType = 1
	ServiceType_SERVICE_TYPE_PROCESSOR   ServiceType = 2
	ServiceType_SERVICE_TYPE_SINK        ServiceType = 3
	ServiceType_SERVICE_TYPE_PIPELINE    ServiceType = 4 // Composite service containing source, processors, and sinks
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_SOURCE",
		2: "SERVICE_TYPE_PROCESSOR",
		3: "SERVICE_TYPE_SINK",
		4: "SERVICE_TYPE_PIPELINE",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_SOURCE":      1,
		"SERVICE_TYPE_PROCESSOR":   2,
		"SERVICE_TYPE_SINK":        3,
		"SERVICE_TYPE_PIPELINE":    4,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{0}
}

// Pipeline run status
type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNKNOWN   RunStatus = 0
	RunStatus_RUN_STATUS_STARTING  RunStatus = 1
	RunStatus_RUN_STATUS_RUNNING   RunStatus = 2
	RunStatus_RUN_STATUS_COMPLETED RunStatus = 3
	RunStatus_RUN_STATUS_FAILED    RunStatus = 4
	RunStatus_RUN_STATUS_STOPPED   RunStatus = 5
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNKNOWN",
		1: "RUN_STATUS_STARTING",
		2: "RUN_STATUS_RUNNING",
		3: "RUN_STATUS_COMPLETED",
		4: "RUN_STATUS_FAILED",
		5: "RUN_STATUS_STOPPED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNKNOWN":   0,
		"RUN_STATUS_STARTING":  1,
		"RUN_STATUS_RUNNING":   2,
		"RUN_STATUS_COMPLETED": 3,
		"RUN_STATUS_FAILED":    4,
		"RUN_STATUS_STOPPED":   5,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_plane_proto_enumTypes[1].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_proto_control_plane_proto_enumTypes[1]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{1}
}

// Service registration information
type ServiceInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceId        string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceType      ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=flowctl.ServiceType" json:"service_type,omitempty"`
	InputEventTypes  []string               `protobuf:"bytes,3,rep,name=input_event_types,json=inputEventTypes,proto3" json:"input_event_types,omitempty"`                                    // For processors only
	OutputEventTypes []string               `protobuf:"bytes,4,rep,name=output_event_types,json=outputEventTypes,proto3" json:"output_event_types,omitempty"`                                 // For sources and processors
	HealthEndpoint   string                 `protobuf:"bytes,5,opt,name=health_endpoint,json=healthEndpoint,proto3" json:"health_endpoint,omitempty"`                                         // Prometheus metrics endpoint
	MaxInflight      int32                  `protobuf:"varint,6,opt,name=max_inflight,json=maxInflight,proto3" json:"max_inflight,omitempty"`                                                 // Back-pressure credits
	Metadata         map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional service metadata
	ComponentId      string                 `protobuf:"bytes,8,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`                                                  // Component ID from pipeline YAML (e.g., "stellar-source")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceInfo) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceInfo) GetInputEventTypes() []string {
	if x != nil {
		return x.InputEventTypes
	}
	return nil
}

func (x *ServiceInfo) GetOutputEventTypes() []string {
	if x != nil {
		return x.OutputEventTypes
	}
	return nil
}

func (x *ServiceInfo) GetHealthEndpoint() string {
	if x != nil {
		return x.HealthEndpoint
	}
	return ""
}

func (x *ServiceInfo) GetMaxInflight() int32 {
	if x != nil {
		return x.MaxInflight
	}
	return 0
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInfo) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

// Registration acknowledgment
type RegistrationAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TopicNames     []string               `protobuf:"bytes,2,rep,name=topic_names,json=topicNames,proto3" json:"topic_names,omitempty"`                                                                                       // Kafka topics to consume/produce
	ConnectionInfo map[string]string      `protobuf:"bytes,3,rep,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Connection details (endpoints, creds)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_proto_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationAck) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegistrationAck) GetTopicNames() []string {
	if x != nil {
		return x.TopicNames
	}
	return nil
}

func (x *RegistrationAck) GetConnectionInfo() map[string]string {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

// ServiceHeartbeat message
type ServiceHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Service-specific metrics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeat) Reset() {
	*x = ServiceHeartbeat{}
	mi := &file_proto_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeat) ProtoMessage() {}

func (x *ServiceHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeat.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceHeartbeat) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceHeartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServiceHeartbeat) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Service status information
type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceType   ServiceType            `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=flowctl.ServiceType" json:"service_type,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,3,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ComponentId   string                 `protobuf:"bytes,6,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"` // Component ID from pipeline YAML
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_proto_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceStatus) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceStatus) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceStatus) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *ServiceStatus) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *ServiceStatus) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ServiceStatus) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

// List of registered services
type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceStatus       `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_proto_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceList) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

// Metrics for a pipeline run
type RunMetrics struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	EventsProcessed  int64                        `protobuf:"varint,1,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	EventsPerSecond  float64                      `protobuf:"fixed64,2,opt,name=events_per_second,json=eventsPerSecond,proto3" json:"events_per_second,omitempty"`
	BytesProcessed   int64                        `protobuf:"varint,3,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	ComponentMetrics map[string]*ComponentMetrics `protobuf:"bytes,4,rep,name=component_metrics,json=componentMetrics,proto3" json:"component_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunMetrics) Reset() {
	*x = RunMetrics{}
	mi := &file_proto_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMetrics) ProtoMessage() {}

func (x *RunMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMetrics.ProtoReflect.Descriptor instead.
func (*RunMetrics) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *RunMetrics) GetEventsProcessed() int64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *RunMetrics) GetEventsPerSecond() float64 {
	if x != nil {
		return x.EventsPerSecond
	}
	return 0
}

func (x *RunMetrics) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *RunMetrics) GetComponentMetrics() map[string]*ComponentMetrics {
	if x != nil {
		return x.ComponentMetrics
	}
	return nil
}

// Per-component metrics
type ComponentMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventsIn         int64                  `protobuf:"varint,1,opt,name=events_in,json=eventsIn,proto3" json:"events_in,omitempty"`
	EventsOut        int64                  `protobuf:"varint,2,opt,name=events_out,json=eventsOut,proto3" json:"events_out,omitempty"`
	BytesIn          int64                  `protobuf:"varint,3,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut         int64                  `protobuf:"varint,4,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	ProcessingTimeMs float64                `protobuf:"fixed64,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComponentMetrics) Reset() {
	*x = ComponentMetrics{}
	mi := &file_proto_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentMetrics) ProtoMessage() {}

func (x *ComponentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentMetrics.ProtoReflect.Descriptor instead.
func (*ComponentMetrics) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *ComponentMetrics) GetEventsIn() int64 {
	if x != nil {
		return x.EventsIn
	}
	return 0
}

func (x *ComponentMetrics) GetEventsOut() int64 {
	if x != nil {
		return x.EventsOut
	}
	return 0
}

func (x *ComponentMetrics) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *ComponentMetrics) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *ComponentMetrics) GetProcessingTimeMs() float64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// Pipeline run record
type PipelineRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineName  string                 `protobuf:"bytes,3,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	Status        RunStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ConfigYaml    string                 `protobuf:"bytes,7,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	Metrics       *RunMetrics            `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	ComponentIds  []string               `protobuf:"bytes,10,rep,name=component_ids,json=componentIds,proto3" json:"component_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRun) Reset() {
	*x = PipelineRun{}
	mi := &file_proto_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRun) ProtoMessage() {}

func (x *PipelineRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRun.ProtoReflect.Descriptor instead.
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PipelineRun) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineRun) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *PipelineRun) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *PipelineRun) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PipelineRun) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *PipelineRun) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *PipelineRun) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PipelineRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PipelineRun) GetComponentIds() []string {
	if x != nil {
		return x.ComponentIds
	}
	return nil
}

// Create pipeline run request
type CreatePipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PipelineName  string                 `protobuf:"bytes,2,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	ConfigYaml    string                 `protobuf:"bytes,3,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	ComponentIds  []string               `protobuf:"bytes,4,rep,name=component_ids,json=componentIds,proto3" json:"component_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePipelineRunRequest) Reset() {
	*x = CreatePipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePipelineRunRequest) ProtoMessage() {}

func (x *CreatePipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePipelineRunRequest.ProtoReflect.Descriptor instead.
func (*CreatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

func (x *CreatePipelineRunRequest) GetComponentIds() []string {
	if x != nil {
		return x.ComponentIds
	}
	return nil
}

// Update pipeline run request
type UpdatePipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        RunStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`
	Metrics       *RunMetrics            `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePipelineRunRequest) Reset() {
	*x = UpdatePipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePipelineRunRequest) ProtoMessage() {}

func (x *UpdatePipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePipelineRunRequest.ProtoReflect.Descriptor instead.
func (*UpdatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *UpdatePipelineRunRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *UpdatePipelineRunRequest) GetMetrics() *RunMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *UpdatePipelineRunRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get pipeline run request
type GetPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRunRequest) Reset() {
	*x = GetPipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRunRequest) ProtoMessage() {}

func (x *GetPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *GetPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// List pipeline runs request
type ListPipelineRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineName  string                 `protobuf:"bytes,1,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"` // Optional: filter by pipeline name
	Status        RunStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=flowctl.RunStatus" json:"status,omitempty"`         // Optional: filter by status
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Optional: limit number of results (default: 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsRequest) Reset() {
	*x = ListPipelineRunsRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsRequest) ProtoMessage() {}

func (x *ListPipelineRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsRequest.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *ListPipelineRunsRequest) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *ListPipelineRunsRequest) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNKNOWN
}

func (x *ListPipelineRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// List pipeline runs response
type ListPipelineRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*PipelineRun         `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelineRunsResponse) Reset() {
	*x = ListPipelineRunsResponse{}
	mi := &file_proto_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelineRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelineRunsResponse) ProtoMessage() {}

func (x *ListPipelineRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelineRunsResponse.ProtoReflect.Descriptor instead.
func (*ListPipelineRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *ListPipelineRunsResponse) GetRuns() []*PipelineRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

// Stop pipeline run request
type StopPipelineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPipelineRunRequest) Reset() {
	*x = StopPipelineRunRequest{}
	mi := &file_proto_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPipelineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPipelineRunRequest) ProtoMessage() {}

func (x *StopPipelineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPipelineRunRequest.ProtoReflect.Descriptor instead.
func (*StopPipelineRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *StopPipelineRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_proto_control_plane_proto protoreflect.FileDescriptor

const file_proto_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x19proto/control_plane.proto\x12\aflowctl\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n" +
	"\vServiceInfo\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.flowctl.ServiceTypeR\vserviceType\x12*\n" +
	"\x11input_event_types\x18\x03 \x03(\tR\x0finputEventTypes\x12,\n" +
	"\x12output_event_types\x18\x04 \x03(\tR\x10outputEventTypes\x12'\n" +
	"\x0fhealth_endpoint\x18\x05 \x01(\tR\x0ehealthEndpoint\x12!\n" +
	"\fmax_inflight\x18\x06 \x01(\x05R\vmaxInflight\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".flowctl.ServiceInfo.MetadataEntryR\bmetadata\x12!\n" +
	"\fcomponent_id\x18\b \x01(\tR\vcomponentId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x0fRegistrationAck\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vtopic_names\x18\x02 \x03(\tR\n" +
	"topicNames\x12U\n" +
	"\x0fconnection_info\x18\x03 \x03(\v2,.flowctl.RegistrationAck.ConnectionInfoEntryR\x0econnectionInfo\x1aA\n" +
	"\x13ConnectionInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x10ServiceHeartbeat\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\ametrics\x18\x03 \x03(\v2&.flowctl.ServiceHeartbeat.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe7\x02\n" +
	"\rServiceStatus\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x127\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x14.flowctl.ServiceTypeR\vserviceType\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x03 \x01(\bR\tisHealthy\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12=\n" +
	"\ametrics\x18\x05 \x03(\v2#.flowctl.ServiceStatus.MetricsEntryR\ametrics\x12!\n" +
	"\fcomponent_id\x18\x06 \x01(\tR\vcomponentId\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"A\n" +
	"\vServiceList\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.flowctl.ServiceStatusR\bservices\"\xc4\x02\n" +
	"\n" +
	"RunMetrics\x12)\n" +
	"\x10events_processed\x18\x01 \x01(\x03R\x0feventsProcessed\x12*\n" +
	"\x11events_per_second\x18\x02 \x01(\x01R\x0feventsPerSecond\x12'\n" +
	"\x0fbytes_processed\x18\x03 \x01(\x03R\x0ebytesProcessed\x12V\n" +
	"\x11component_metrics\x18\x04 \x03(\v2).flowctl.RunMetrics.ComponentMetricsEntryR\x10componentMetrics\x1a^\n" +
	"\x15ComponentMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.flowctl.ComponentMetricsR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x10ComponentMetrics\x12\x1b\n" +
	"\tevents_in\x18\x01 \x01(\x03R\beventsIn\x12\x1d\n" +
	"\n" +
	"events_out\x18\x02 \x01(\x03R\teventsOut\x12\x19\n" +
	"\bbytes_in\x18\x03 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x04 \x01(\x03R\bbytesOut\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x01R\x10processingTimeMs\"\x93\x03\n" +
	"\vPipelineRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12#\n" +
	"\rpipeline_name\x18\x03 \x01(\tR\fpipelineName\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vconfig_yaml\x18\a \x01(\tR\n" +
	"configYaml\x12-\n" +
	"\ametrics\x18\b \x01(\v2\x13.flowctl.RunMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12#\n" +
	"\rcomponent_ids\x18\n" +
	" \x03(\tR\fcomponentIds\"\x9c\x01\n" +
	"\x18CreatePipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rpipeline_name\x18\x02 \x01(\tR\fpipelineName\x12\x1f\n" +
	"\vconfig_yaml\x18\x03 \x01(\tR\n" +
	"configYaml\x12#\n" +
	"\rcomponent_ids\x18\x04 \x03(\tR\fcomponentIds\"\xa2\x01\n" +
	"\x18UpdatePipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x12-\n" +
	"\ametrics\x18\x03 \x01(\v2\x13.flowctl.RunMetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\".\n" +
	"\x15GetPipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x80\x01\n" +
	"\x17ListPipelineRunsRequest\x12#\n" +
	"\rpipeline_name\x18\x01 \x01(\tR\fpipelineName\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.flowctl.RunStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"D\n" +
	"\x18ListPipelineRunsResponse\x12(\n" +
	"\x04runs\x18\x01 \x03(\v2\x14.flowctl.PipelineRunR\x04runs\"/\n" +
	"\x16StopPipelineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId*\x92\x01\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVICE_TYPE_SOURCE\x10\x01\x12\x1a\n" +
	"\x16SERVICE_TYPE_PROCESSOR\x10\x02\x12\x15\n" +
	"\x11SERVICE_TYPE_SINK\x10\x03\x12\x19\n" +
	"\x15SERVICE_TYPE_PIPELINE\x10\x04*\x9d\x01\n" +
	"\tRunStatus\x12\x16\n" +
	"\x12RUN_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13RUN_STATUS_STARTING\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x04\x12\x16\n" +
	"\x12RUN_STATUS_STOPPED\x10\x052\x91\x05\n" +
	"\fControlPlane\x12:\n" +
	"\bRegister\x12\x14.flowctl.ServiceInfo\x1a\x18.flowctl.RegistrationAck\x12>\n" +
	"\tHeartbeat\x12\x19.flowctl.ServiceHeartbeat\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x10GetServiceStatus\x12\x14.flowctl.ServiceInfo\x1a\x16.flowctl.ServiceStatus\x12<\n" +
	"\fListServices\x12\x16.google.protobuf.Empty\x1a\x14.flowctl.ServiceList\x12L\n" +
	"\x11CreatePipelineRun\x12!.flowctl.CreatePipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12L\n" +
	"\x11UpdatePipelineRun\x12!.flowctl.UpdatePipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12F\n" +
	"\x0eGetPipelineRun\x12\x1e.flowctl.GetPipelineRunRequest\x1a\x14.flowctl.PipelineRun\x12W\n" +
	"\x10ListPipelineRuns\x12 .flowctl.ListPipelineRunsRequest\x1a!.flowctl.ListPipelineRunsResponse\x12H\n" +
	"\x0fStopPipelineRun\x12\x1f.flowctl.StopPipelineRunRequest\x1a\x14.flowctl.PipelineRunB/Z-github.com/withobsrvr/flowctl/proto;flowctlpbb\x06proto3"

var (
	file_proto_control_plane_proto_rawDescOnce sync.Once
	file_proto_control_plane_proto_rawDescData []byte
)

func file_proto_control_plane_proto_rawDescGZIP() []byte {
	file_proto_control_plane_proto_rawDescOnce.Do(func() {
		file_proto_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_plane_proto_rawDesc), len(file_proto_control_plane_proto_rawDesc)))
	})
	return file_proto_control_plane_proto_rawDescData
}

var file_proto_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_control_plane_proto_goTypes = []any{
	(ServiceType)(0),                 // 0: flowctl.ServiceType
	(RunStatus)(0),                   // 1: flowctl.RunStatus
	(*ServiceInfo)(nil),              // 2: flowctl.ServiceInfo
	(*RegistrationAck)(nil),          // 3: flowctl.RegistrationAck
	(*ServiceHeartbeat)(nil),         // 4: flowctl.ServiceHeartbeat
	(*ServiceStatus)(nil),            // 5: flowctl.ServiceStatus
	(*ServiceList)(nil),              // 6: flowctl.ServiceList
	(*RunMetrics)(nil),               // 7: flowctl.RunMetrics
	(*ComponentMetrics)(nil),         // 8: flowctl.ComponentMetrics
	(*PipelineRun)(nil),              // 9: flowctl.PipelineRun
	(*CreatePipelineRunRequest)(nil), // 10: flowctl.CreatePipelineRunRequest
	(*UpdatePipelineRunRequest)(nil), // 11: flowctl.UpdatePipelineRunRequest
	(*GetPipelineRunRequest)(nil),    // 12: flowctl.GetPipelineRunRequest
	(*ListPipelineRunsRequest)(nil),  // 13: flowctl.ListPipelineRunsRequest
	(*ListPipelineRunsResponse)(nil), // 14: flowctl.ListPipelineRunsResponse
	(*StopPipelineRunRequest)(nil),   // 15: flowctl.StopPipelineRunRequest
	nil,                              // 16: flowctl.ServiceInfo.MetadataEntry
	nil,                              // 17: flowctl.RegistrationAck.ConnectionInfoEntry
	nil,                              // 18: flowctl.ServiceHeartbeat.MetricsEntry
	nil,                              // 19: flowctl.ServiceStatus.MetricsEntry
	nil,                              // 20: flowctl.RunMetrics.ComponentMetricsEntry
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 22: google.protobuf.Empty
}
var file_proto_control_plane_proto_depIdxs = []int32{
	0,  // 0: flowctl.ServiceInfo.service_type:type_name -> flowctl.ServiceType
	16, // 1: flowctl.ServiceInfo.metadata:type_name -> flowctl.ServiceInfo.MetadataEntry
	17, // 2: flowctl.RegistrationAck.connection_info:type_name -> flowctl.RegistrationAck.ConnectionInfoEntry
	21, // 3: flowctl.ServiceHeartbeat.timestamp:type_name -> google.protobuf.Timestamp
	18, // 4: flowctl.ServiceHeartbeat.metrics:type_name -> flowctl.ServiceHeartbeat.MetricsEntry
	0,  // 5: flowctl.ServiceStatus.service_type:type_name -> flowctl.ServiceType
	21, // 6: flowctl.ServiceStatus.last_heartbeat:type_name -> google.protobuf.Timestamp
	19, // 7: flowctl.ServiceStatus.metrics:type_name -> flowctl.ServiceStatus.MetricsEntry
	5,  // 8: flowctl.ServiceList.services:type_name -> flowctl.ServiceStatus
	20, // 9: flowctl.RunMetrics.component_metrics:type_name -> flowctl.RunMetrics.ComponentMetricsEntry
	1,  // 10: flowctl.PipelineRun.status:type_name -> flowctl.RunStatus
	21, // 11: flowctl.PipelineRun.start_time:type_name -> google.protobuf.Timestamp
	21, // 12: flowctl.PipelineRun.end_time:type_name -> google.protobuf.Timestamp
	7,  // 13: flowctl.PipelineRun.metrics:type_name -> flowctl.RunMetrics
	1,  // 14: flowctl.UpdatePipelineRunRequest.status:type_name -> flowctl.RunStatus
	7,  // 15: flowctl.UpdatePipelineRunRequest.metrics:type_name -> flowctl.RunMetrics
	1,  // 16: flowctl.ListPipelineRunsRequest.status:type_name -> flowctl.RunStatus
	9,  // 17: flowctl.ListPipelineRunsResponse.runs:type_name -> flowctl.PipelineRun
	8,  // 18: flowctl.RunMetrics.ComponentMetricsEntry.value:type_name -> flowctl.ComponentMetrics
	2,  // 19: flowctl.ControlPlane.Register:input_type -> flowctl.ServiceInfo
	4,  // 20: flowctl.ControlPlane.Heartbeat:input_type -> flowctl.ServiceHeartbeat
	2,  // 21: flowctl.ControlPlane.GetServiceStatus:input_type -> flowctl.ServiceInfo
	22, // 22: flowctl.ControlPlane.ListServices:input_type -> google.protobuf.Empty
	10, // 23: flowctl.ControlPlane.CreatePipelineRun:input_type -> flowctl.CreatePipelineRunRequest
	11, // 24: flowctl.ControlPlane.UpdatePipelineRun:input_type -> flowctl.UpdatePipelineRunRequest
	12, // 25: flowctl.ControlPlane.GetPipelineRun:input_type -> flowctl.GetPipelineRunRequest
	13, // 26: flowctl.ControlPlane.ListPipelineRuns:input_type -> flowctl.ListPipelineRunsRequest
	15, // 27: flowctl.ControlPlane.StopPipelineRun:input_type -> flowctl.StopPipelineRunRequest
	3,  // 28: flowctl.ControlPlane.Register:output_type -> flowctl.RegistrationAck
	22, // 29: flowctl.ControlPlane.Heartbeat:output_type -> google.protobuf.Empty
	5,  // 30: flowctl.ControlPlane.GetServiceStatus:output_type -> flowctl.ServiceStatus
	6,  // 31: flowctl.ControlPlane.ListServices:output_type -> flowctl.ServiceList
	9,  // 32: flowctl.ControlPlane.CreatePipelineRun:output_type -> flowctl.PipelineRun
	9,  // 33: flowctl.ControlPlane.UpdatePipelineRun:output_type -> flowctl.PipelineRun
	9,  // 34: flowctl.ControlPlane.GetPipelineRun:output_type -> flowctl.PipelineRun
	14, // 35: flowctl.ControlPlane.ListPipelineRuns:output_type -> flowctl.ListPipelineRunsResponse
	9,  // 36: flowctl.ControlPlane.StopPipelineRun:output_type -> flowctl.PipelineRun
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_control_plane_proto_init() }
func file_proto_control_plane_proto_init() {
	if File_proto_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_plane_proto_rawDesc), len(file_proto_control_plane_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_plane_proto_goTypes,
		DependencyIndexes: file_proto_control_plane_proto_depIdxs,
		EnumInfos:         file_proto_control_plane_proto_enumTypes,
		MessageInfos:      file_proto_control_plane_proto_msgTypes,
	}.Build()
	File_proto_control_plane_proto = out.File
	file_proto_control_plane_proto_goTypes = nil
	file_proto_control_plane_proto_depIdxs = nil
}
